import { useTheme } from '@/store/ThemeContext';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Platform, ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View, useWindowDimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const SellerPolicy = () => {
    const { isDarkMode } = useTheme();
    const router = useRouter();
    const insets = useSafeAreaInsets();
    const { width } = useWindowDimensions();
    const isDesktop = width > 768;

    const theme = {
        background: isDarkMode ? '#000000' : '#F8F9FA',
        text: isDarkMode ? '#FFFFFF' : '#121212',
        subtext: isDarkMode ? '#888888' : '#666666',
        card: isDarkMode ? '#111111' : '#FFFFFF',
        border: isDarkMode ? '#222222' : '#E5E5EA',
        accent: isDarkMode ? '#FFFFFF' : '#000000',
        sectionBg: isDarkMode ? '#111111' : '#FFFFFF',
    };

    const PolicySection = ({ title, children, number }: { title: string, children: React.ReactNode, number?: string }) => (
        <View style={[styles.sectionContainer, { borderBottomColor: theme.border }]}>
            <View style={styles.sectionHeader}>
                {number && <Text style={[styles.sectionNumber, { color: theme.subtext }]}>{number}</Text>}
                <Text style={[styles.sectionTitle, { color: theme.text }]}>{title.toUpperCase()}</Text>
            </View>
            <View style={styles.sectionContent}>
                {children}
            </View>
        </View>
    );

    const BulletPoint = ({ text, title }: { text: string, title?: string }) => (
        <View style={styles.bulletRow}>
            <View style={[styles.bulletDot, { backgroundColor: theme.text + '40' }]} />
            <View style={{ flex: 1 }}>
                <Text style={[styles.bulletText, { color: theme.text }]}>
                    {title && <Text style={{ fontWeight: '900' }}>{title}: </Text>}
                    {text}
                </Text>
            </View>
        </View>
    );

    const HighlightBox = ({ text, title }: { text: string, title?: string }) => (
        <View style={[styles.highlightBox, { backgroundColor: theme.text + '05', borderColor: theme.text + '15' }]}>
            {title && <Text style={[styles.highlightTitle, { color: theme.text }]}>{title}</Text>}
            <Text style={[styles.highlightText, { color: theme.text }]}>{text}</Text>
        </View>
    );

    return (
        <View style={[styles.container, { backgroundColor: theme.background }]}>
            <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
            
            {/* Header */}
            <View style={[styles.header, { paddingTop: insets.top + 20, borderBottomColor: theme.border }]}>
                <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
                    <Feather name="arrow-left" size={24} color={theme.text} />
                </TouchableOpacity>
                <View>
                    <Text style={[styles.headerSubtitle, { color: theme.subtext }]}>PARTNER AGREEMENT</Text>
                    <Text style={[styles.headerTitle, { color: theme.text }]}>Seller Policy</Text>
                </View>
                <View style={{ width: 40 }} />
            </View>

            <ScrollView 
                contentContainerStyle={[styles.scrollContent, isDesktop && { paddingHorizontal: (width - 900) / 2 }]}
                showsVerticalScrollIndicator={false}
            >
                <View style={styles.introCard}>
                    <Text style={[styles.mainTitle, { color: theme.text }]}>E-Commerce Services Agreement</Text>
                    <Text style={[styles.legalNotice, { color: theme.subtext }]}>
                        This document is an electronic record under the Information Technology Act, 2000. It is generated by a computer system and does not require any physical or digital signature.
                    </Text>
                    <HighlightBox 
                        title="EFFECTIVE DATE"
                        text="This Agreement shall be deemed effective from the date you click the 'I Agree' button after completing the Seller Registration Form." 
                    />
                </View>

                {/* Parties */}
                <PolicySection title="Parties to the Agreement">
                    <BulletPoint title="Merchant (Seller)" text="You (an individual or legal entity) competent to contract under Indian laws." />
                    <BulletPoint title="Service Provider" text="BADHEE G PRIVATE LIMITED, KHURI BARI LAXAMANGARH, SIKAR, RAJASTHAN." />
                </PolicySection>

                {/* 1. Definitions */}
                <PolicySection title="Definitions" number="01">
                    <BulletPoint title="Affiliate" text="Any entity controlling, controlled by, or under common control with a Party." />
                    <BulletPoint title="Brand" text="Refers to 'BADHEE G™' or any future brand name chosen by the Service Provider." />
                    <BulletPoint title="Confidential Information" text="Business info, advertising plans, financial data, and End Customer Database." />
                    <BulletPoint title="End Customer Database" text="Proprietary IP of Service Provider containing all customer trends and data." />
                    <BulletPoint title="Transaction Support Services" text="Includes Product Listing, Fulfillment, Logistics, and Customer Support." />
                </PolicySection>

                {/* 2. Interpretation */}
                <PolicySection title="Interpretation" number="02">
                    <BulletPoint text="Person/Party includes natural persons, companies, LLPs, trusts, etc." />
                    <BulletPoint text="Words in singular include plural and vice versa." />
                    <BulletPoint text="Written/Signature includes emails and electronic forms." />
                </PolicySection>

                {/* 3. Services */}
                <PolicySection title="Services" number="03">
                    <BulletPoint text="The Merchant appoints Service Provider to sell products on its platform." />
                    <BulletPoint text="Service Provider may refuse service for defamation or law violations." />
                    <BulletPoint text="Merchant has the option to choose or opt-out of warehousing services." />
                </PolicySection>

                {/* 4. Advertising & Marketing */}
                <PolicySection title="Advertising & Marketing" number="04">
                    <BulletPoint text="Service Provider has full rights over platform design and product ranking." />
                    <BulletPoint text="All earnings from platform advertisements belong to the Service Provider." />
                    <HighlightBox text="If any advertisement violates law, the Merchant must inform the Service Provider with a legal opinion for immediate removal." />
                </PolicySection>

                {/* 6. Payment Terms */}
                <PolicySection title="Payment Terms" number="06">
                    <BulletPoint text="Service Fee is decided in Commercial Terms and can be modified via email." />
                    <BulletPoint text="Service Provider may deduct fees from customer payments." />
                    <HighlightBox text="If fees cannot be deducted, Merchant must pay within 10 days of billing." />
                </PolicySection>

                {/* 7. Service Provider Responsibilities */}
                <PolicySection title="Provider Responsibilities" number="07">
                    <BulletPoint text="Operate platform smoothly and provide logistics support." />
                    <BulletPoint text="Maintain website registration and payment gateway contracts." />
                    <HighlightBox title="PRICE REVISION" text="Any revision in item price requires mutual written consent. No modification is effective without prior approval from both parties." />
                </PolicySection>

                {/* 8. Merchant Responsibilities */}
                <PolicySection title="Merchant Responsibilities" number="08">
                    <BulletPoint title="Stock" text="Maintain sufficient stock and hand over orders on time." />
                    <BulletPoint title="Sale Price" text="Must include all taxes/packaging and cannot exceed MRP." />
                    <BulletPoint title="After-Sales" text="Responsibility for warranty and repairs lies solely with the Merchant." />
                    <BulletPoint title="Branding" text="No brand names other than Service Provider's on packaging." />
                    <BulletPoint title="Ownership" text="Ownership and risk remain with the Merchant until delivery." />
                    <HighlightBox title="GRIEVANCE" text="Service Provider's Grievance Officer's decision regarding refunds/returns is binding on the Merchant." />
                </PolicySection>

                {/* 11. Indemnification */}
                <PolicySection title="Liability & Indemnity" number="11">
                    <BulletPoint text="Merchant shall indemnify Provider against fraud or breach of law." />
                    <BulletPoint text="Provider's liability limited to last 12 months' fees or product cost." />
                    <HighlightBox text="Provider may sell Merchant's goods or withhold funds to recover losses." />
                </PolicySection>

                {/* 13. Termination */}
                <PolicySection title="Term & Termination" number="13">
                    <BulletPoint text="Agreement remains valid until terminated." />
                    <BulletPoint text="Either party can terminate with a 30-day written notice." />
                    <BulletPoint text="Immediate termination possible for insolvency or business shutdown." />
                </PolicySection>

                {/* 16. Dispute Resolution */}
                <PolicySection title="Dispute Resolution" number="16">
                    <BulletPoint text="First attempt: Amicable settlement through mutual discussion." />
                    <BulletPoint text="Escalation: Refer to Arbitration if unresolved within 30 days." />
                    <HighlightBox title="ARBITRATION" text="Seat: Jaipur, Rajasthan. Language: English/Hindi. Tribunal: Panel of 3 Arbitrators." />
                </PolicySection>

                {/* 17. General Clauses */}
                <PolicySection title="General Clauses" number="17">
                    <BulletPoint title="Relationship" text="Independent Contractor (Principal-to-Principal)." />
                    <BulletPoint title="Amendments" text="Provider may update terms at any time; continued use equals acceptance." />
                    <BulletPoint title="Jurisdiction" text="Only courts in JAIPUR shall have exclusive jurisdiction." />
                </PolicySection>

                <View style={{ height: 100 }} />
            </ScrollView>
        </View>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1 },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingBottom: 20,
        borderBottomWidth: 1,
    },
    backBtn: { padding: 4 },
    headerSubtitle: {
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 2,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: '900',
        letterSpacing: -0.5,
    },
    scrollContent: {
        padding: 24,
    },
    introCard: {
        marginBottom: 40,
    },
    mainTitle: {
        fontSize: 28,
        fontWeight: '900',
        lineHeight: 34,
        marginBottom: 16,
        letterSpacing: -1,
    },
    legalNotice: {
        fontSize: 14,
        lineHeight: 22,
        marginBottom: 24,
        fontWeight: '500',
    },
    sectionContainer: {
        paddingVertical: 32,
        borderBottomWidth: 1,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'baseline',
        gap: 12,
        marginBottom: 20,
    },
    sectionNumber: {
        fontSize: 12,
        fontWeight: '900',
        opacity: 0.3,
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '900',
        letterSpacing: 2,
    },
    sectionContent: {
        gap: 16,
    },
    bulletRow: {
        flexDirection: 'row',
        gap: 12,
    },
    bulletDot: {
        width: 4,
        height: 4,
        borderRadius: 2,
        marginTop: 8,
    },
    bulletText: {
        fontSize: 15,
        lineHeight: 22,
        fontWeight: '500',
    },
    highlightBox: {
        padding: 20,
        borderRadius: 16,
        borderWidth: 1,
        marginTop: 8,
    },
    highlightTitle: {
        fontSize: 11,
        fontWeight: '900',
        letterSpacing: 1,
        marginBottom: 8,
        opacity: 0.6,
    },
    highlightText: {
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 20,
    },
});

export default SellerPolicy;
